version: '2'

services:
  db:
    image: postgres:9.5-alpine
    ports:
      - '5432:5432'

  website:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3035:3035'
      - '5000:5000'
    command: 'foreman start'
    volumes:
      - '.:/usr/src/app'
    environment:       
      RAILS_ENV: development
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: 'db'