# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcd7f2941557b2ea9a20f138815144adb8ffa295006f600ae3c43c0a4a1059331fcea2f61fdcbc9ad6c3762461d32048247fc26bcbc9bf0cdb3c117974c7658d

test:
  secret_key_base: 4b9b308e29b16b9944389e8326061ab645f0da5fb32a7c15a368d1406c329c18453301215e8ba1ce20a8f76b552c4212852d56a5af87bc5c0a5d7185425903a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
